behaviors:
  PadelAgent:
    trainer_type: ppo
    summary_freq: 25000
    max_steps: 1000000
    keep_checkpoints: 5
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: linear
      batch_size: 512
      buffer_size: 20480
      beta: 0.005
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      num_epoch: 3
    network_settings:
      hidden_units: 64
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    self_play:
          save_steps: 50000
          swap_steps: 25000
          team_change: 200000
          window: 15
          play_against_latest_model_ratio: 0.5
          initial_elo: 1200.0
